function [] = VisualizeSimulation(parameters, tx)
% Visualize signal patwhay in the medium generated by map 

    % For clarity
    grid = parameters.grid; 
    param = parameters.param;
    
    % Parameters computation
    to_px = @(mm) round(mm/grid.step); 
    Nz = to_px(grid.depth);    % Number of point in the direction 1 (depth - Z)
    Nx = to_px(grid.width);    % Number of point in the direction 2 (width - X)

    X = 0:grid.step:grid.width-grid.step; X = X -mean(X);
    Z = flipud(0:grid.step:grid.depth-grid.step);
    SnapNb = param.length/0.5;      % Number of snap per transmitter, one stap recorded every 0.5 us. . 
    
    figure
    for i = 1:SnapNb
        snap_name = sprintf('~/Documents/SIMSONIC/Simulation/simulation_rough_interface/tx_%02d/T11_%03d.snp2D',tx, i);
        snap = SimSonic2DReadSnp2D(snap_name);
        
        % Plot
        pcolor(X, Z, snap.Data)
        axis ij image, shading interp
        pause(0.1) % Pause between the display of each snap
    end 
end